### ISSUE TITLE
3D Modeling - Trees

### ISSUE THREAD

**Issue by BlocKoopa** [BlocKoopa/KnightsCapstone#5]
Make 2 types of trees, 1 big & 1 small, for the Chess level.

**Comment by BrawlerClaws67** [comment]
[Tree No 2 Model 3DS Max Files.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410912/Tree.No.2.Model.3DS.Max.Files.zip)
[Tree No 2 3D Model FBX.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410913/Tree.No.2.3D.Model.FBX.zip)
[Tree No 2 Texture PDN File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410914/Tree.No.2.Texture.PDN.File.zip)
[Tree No 2 Texture.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410915/Tree.No.2.Texture.zip)
[Tree No 2 Texture Template.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410916/Tree.No.2.Texture.Template.zip)
[Tree No 2 Model Unwrap File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410917/Tree.No.2.Model.Unwrap.File.zip)
[Tree No 1 Model UVW File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410929/Tree.No.1.Model.UVW.File.zip)
[Tree No 1 Texture Template.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410930/Tree.No.1.Texture.Template.zip)
[Tree No 1 Texture.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410931/Tree.No.1.Texture.zip)
[Tree No 1 Texture PDN File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410932/Tree.No.1.Texture.PDN.File.zip)
[Tree No 1 3D Model FBX.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410933/Tree.No.1.3D.Model.FBX.zip)
[Tree No 1 Model 3DS Max.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4410934/Tree.No.1.Model.3DS.Max.zip)


Here are the files for the Tree No 2 Model. I had to put them all in some Zip folders to upload them, but they're all also in the Google Drive.

**Comment by BrawlerClaws67** [comment]
[Tree Grouping Model 3DS Max Files.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457920/Tree.Grouping.Model.3DS.Max.Files.zip)
[Tree Grouping 3D Model FBX.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457921/Tree.Grouping.3D.Model.FBX.zip)
[Tree Grouping Model Texture PDN File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457923/Tree.Grouping.Model.Texture.PDN.File.zip)
[Tree Grouping Model Texture.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457924/Tree.Grouping.Model.Texture.zip)
[Tree Grouping Model Texture Template.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457925/Tree.Grouping.Model.Texture.Template.zip)
[Tree Grouping Model Unwrap File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457926/Tree.Grouping.Model.Unwrap.File.zip)

Here are the files for what we are now going to use as the 2x1 tree model, what I'm calling Tree Grouping. I think that we are using Tree No 2 Model as the 1x1 tree, and I guess the Tree No 1 Model is on the sidelines for now. As usual, these files are all in the Google Drive.
