### ISSUE TITLE
3D Modeling - Rickshaw

### ISSUE THREAD

**Issue by BlocKoopa** [BlocKoopa/KnightsCapstone#6]
Make a rickshaw for the Shogi level.

**Comment by BrawlerClaws67** [comment]
Here are all of the Rickshaw 3D Model files. I had to put them into Zip folders to upload them, but they're all also in the Google Drive.
[Rickshaw Model Unwrap File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4411078/Rickshaw.Model.Unwrap.File.zip)
[Rickshaw Model Texture Template.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4411079/Rickshaw.Model.Texture.Template.zip)
[Rickshaw Model Texture.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4411080/Rickshaw.Model.Texture.zip)
[Rickshaw Model Texture PDN File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4411081/Rickshaw.Model.Texture.PDN.File.zip)
[Rickshaw 3D Model FBX.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4411082/Rickshaw.3D.Model.FBX.zip)
[Rickshaw 3D Model 3DS Max Files.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4411083/Rickshaw.3D.Model.3DS.Max.Files.zip)

**Comment by BrawlerClaws67** [comment]
[Rickshaw Model 3DS Max POST MERGE TAKE 2.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457910/Rickshaw.Model.3DS.Max.POST.MERGE.TAKE.2.zip)
[Rickshaw 3D Model TAKE 2 FBX.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457911/Rickshaw.3D.Model.TAKE.2.FBX.zip)
[Rickshaw Model TAKE 2 Texture PDN File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457912/Rickshaw.Model.TAKE.2.Texture.PDN.File.zip)
[Rickshaw Model TAKE 2 Texture.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457914/Rickshaw.Model.TAKE.2.Texture.zip)
[Rickshaw Model TAKE 2 Texture Template.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457915/Rickshaw.Model.TAKE.2.Texture.Template.zip)
[Rickshaw Model TAKE 2 Unwrap File.zip](https://github.com/BlocKoopa/KnightsCapstone/files/4457917/Rickshaw.Model.TAKE.2.Unwrap.File.zip)

Here's the fixed versions of the Rickshaw 3D Model files. I made the wheels and the handle parts thicker so they look better in the engine.
